//{{NO_DEPENDENCIES}}
//
// This file is used and maintained by ResourceStudio.
//
// If you add IDs, be sure to change the appropriate _APS_NEXT.. constant
// at the bottom of the file.
//

#define IDR_MAINFRAME				            2
#define IDR_MDIDOCTYPE							3
#define IDD_ABOUTBOX							100

#define _APS_NEXT_RESOURCE_VALUE				101
#define _APS_NEXT_CONTROL_VALUE					101
#define _APS_NEXT_SYMED_VALUE					101
#define _APS_NEXT_COMMAND_VALUE					32768
#define IDC_STATIC                              65535
#define IDM_ITEM2                               32001
#define ID_FrMod_InCnd                          32002
#define IDC_EDIT1                               3000
#define IDI_ICON1                               103
#define IDD_FrModInCnd                          102
#define IDC_EDIT2                               3002
#define IDC_EDIT3                               3003
#define IDC_EDIT4                               3004
#define IDC_EDIT5                               3005
#define IDC_EDIT6                               3006
#define IDD_DIALOG1                                     105
#define IDC_TABCONTROL1                                3003
#define IDD_PATH                                        104
#define ID_PathDlg                                        4000
#define IDD_DIALOG2                                     106
#define IDM_ITEM1                                     32768
